const { app, BrowserWindow, Tray, Menu, screen, globalShortcut, ipcMain, nativeImage, shell } = require('electron');
const path = require('path');
const fs = require('fs');
const { exec, execFile } = require('child_process');
const { checkForUpdates, downloadUpdate } = require('./updater');

let mainWindow = null;
let tray = null;
let boostLevel = 100;
let isMuted = false;
let limiterEnabled = true;

const APO_CONFIG_DIR = 'C:\\Program Files\\EqualizerAPO\\config';
const APO_CONFIG_PATH = path.join(APO_CONFIG_DIR, 'config.txt');
const BRIDGE_EXE_PATH = path.join(__dirname, 'bin', 'VolumeBridge.exe');

// Helper to run VolumeBridge CLI commands (one-shot)
function runBridge(args) {
  return new Promise((resolve) => {
    if (!fs.existsSync(BRIDGE_EXE_PATH)) {
      return resolve(null);
    }
    execFile(BRIDGE_EXE_PATH, args, { encoding: 'utf8' }, (err, stdout) => {
      if (err || !stdout) return resolve(null);
      try {
        const json = JSON.parse(stdout.trim());
        resolve(json);
      } catch {
        resolve(null);
      }
    });
  });
}

function getAudioEngineStatus() {
  const apoInstalled = fs.existsSync(APO_CONFIG_PATH);
  const gainDb = boostLevel > 100 ? (20 * Math.log10(boostLevel / 100)).toFixed(1) : '0.0';

  return {
    installed: apoInstalled,
    path: APO_CONFIG_PATH,
    gainDb: gainDb,
    boostLevel: boostLevel,
    engine: 'equalizer-apo',
  };
}

function updateApoPreamp(level) {
  try {
    const gainDb = level <= 100 ? '0.0' : (20 * Math.log10(level / 100)).toFixed(1);
    const content = `# Generated by VolumeMax Windows Booster\n# Gain corresponding to ${level}%\nPreamp: ${parseFloat(gainDb) >= 0 && level > 100 ? '+' : ''}${gainDb} dB\n`;

    if (fs.existsSync(APO_CONFIG_PATH)) {
      fs.writeFileSync(APO_CONFIG_PATH, content, 'utf8');
    } else {
      // Cria a pasta ou salva localmente se não existir
      try {
        if (!fs.existsSync(APO_CONFIG_DIR)) {
          fs.mkdirSync(APO_CONFIG_DIR, { recursive: true });
        }
        fs.writeFileSync(APO_CONFIG_PATH, content, 'utf8');
      } catch {
        const fallback = path.join(app.getPath('userData'), 'apo_config.txt');
        fs.writeFileSync(fallback, content, 'utf8');
      }
    }
  } catch (err) {
    console.error('Error writing Equalizer APO config:', err);
  }
}

function setBoost(level) {
  boostLevel = Math.max(0, Math.min(500, level));
  updateTrayMenu();

  if (boostLevel <= 100) {
    // 0% a 100%: controla o volume nativo do Windows e zera o Preamp
    const winVol = (boostLevel / 100).toFixed(2);
    runBridge(['set-volume', winVol]);
    updateApoPreamp(100);
  } else {
    // Acima de 100%: fixa o volume do Windows em 100% e aplica o ganho no Equalizer APO
    runBridge(['set-volume', '1.0']);
    updateApoPreamp(boostLevel);
  }

  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('boost-changed', boostLevel);
  }
}

function setMute(mute) {
  isMuted = mute;
  runBridge(['set-mute', mute ? '1' : '0']);
}

// Calcula a posição da janela no canto inferior direito logo acima da bandeja
function getTrayPosition() {
  if (!mainWindow) return { x: 0, y: 0 };
  
  const [winWidth, winHeight] = mainWindow.getSize();
  const primaryDisplay = screen.getPrimaryDisplay();
  const { width: screenWidth, height: screenHeight } = primaryDisplay.workAreaSize;

  let x = screenWidth - winWidth - 12;
  let y = screenHeight - winHeight - 12;

  if (tray) {
    const trayBounds = tray.getBounds();
    if (trayBounds && trayBounds.width > 0 && trayBounds.height > 0) {
      x = Math.round(trayBounds.x + (trayBounds.width / 2) - (winWidth / 2));
      
      if (x + winWidth > screenWidth - 10) {
        x = screenWidth - winWidth - 10;
      }
      if (x < 10) {
        x = 10;
      }

      if (trayBounds.y > screenHeight / 2) {
        y = Math.round(trayBounds.y - winHeight - 8);
      } else {
        y = Math.round(trayBounds.y + trayBounds.height + 8);
      }
    }
  }

  return { x, y };
}

function showWindow() {
  if (!mainWindow || mainWindow.isDestroyed()) return;
  const { x, y } = getTrayPosition();
  mainWindow.setPosition(x, y, false);
  mainWindow.show();
  mainWindow.focus();
}

function toggleWindow() {
  if (!mainWindow || mainWindow.isDestroyed()) return;
  if (mainWindow.isVisible()) {
    mainWindow.hide();
  } else {
    showWindow();
  }
}

function createWindow() {
  const iconIcoPath = path.join(__dirname, '../assets/icon.ico');
  const iconPngPath = path.join(__dirname, '../assets/icon.png');
  const chosenIcon = fs.existsSync(iconIcoPath) ? iconIcoPath : (fs.existsSync(iconPngPath) ? iconPngPath : undefined);

  mainWindow = new BrowserWindow({
    width: 360,
    height: 600,
    frame: false,
    resizable: false,
    transparent: false,
    show: false,
    skipTaskbar: true,
    alwaysOnTop: true,
    backgroundColor: '#0D0D0F',
    icon: chosenIcon,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  const isDev = process.env.VITE_DEV_SERVER_URL;
  if (isDev) {
    mainWindow.loadURL(process.env.VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(path.join(__dirname, '../dist/index.html'));
  }

  // Fecha flyout ao perder foco
  mainWindow.on('blur', () => {
    if (mainWindow && !mainWindow.isDestroyed() && mainWindow.isVisible()) {
      mainWindow.hide();
    }
  });

  mainWindow.on('close', (e) => {
    if (!app.isQuitting) {
      e.preventDefault();
      mainWindow.hide();
    }
  });
}

function createTray() {
  const iconPath = path.join(__dirname, '../assets/icon.ico');
  const fallbackPng = path.join(__dirname, '../assets/icon.png');
  let trayIcon;

  try {
    if (fs.existsSync(iconPath)) {
      trayIcon = nativeImage.createFromPath(iconPath).resize({ width: 16, height: 16 });
    } else if (fs.existsSync(fallbackPng)) {
      trayIcon = nativeImage.createFromPath(fallbackPng).resize({ width: 16, height: 16 });
    } else {
      trayIcon = nativeImage.createEmpty();
    }
  } catch {
    trayIcon = nativeImage.createEmpty();
  }

  tray = new Tray(trayIcon);
  tray.setToolTip(`VolumeMax — ${boostLevel}%`);

  tray.on('click', () => {
    toggleWindow();
  });

  updateTrayMenu();
}

function updateTrayMenu() {
  if (!tray) return;

  const presets = [100, 150, 200, 300, 500];
  const contextMenu = Menu.buildFromTemplate([
    {
      label: `VolumeMax: ${boostLevel}% (Equalizer APO)`,
      enabled: false,
    },
    { type: 'separator' },
    {
      label: 'Abrir Painel',
      click: () => showWindow(),
    },
    { type: 'separator' },
    ...presets.map((p) => ({
      label: `${p}%${p === boostLevel ? ' ✓' : ''}`,
      click: () => setBoost(p),
    })),
    { type: 'separator' },
    {
      label: isMuted ? 'Desmutar' : 'Mutar',
      click: () => setMute(!isMuted),
    },
    { type: 'separator' },
    {
      label: '❌ Fechar Aplicativo',
      click: () => {
        app.isQuitting = true;
        app.quit();
      },
    },
  ]);

  tray.setToolTip(`VolumeMax — ${boostLevel}%`);
  tray.setContextMenu(contextMenu);
}

function registerHotkeys() {
  globalShortcut.register('Ctrl+Shift+Up', () => {
    setBoost(Math.min(500, boostLevel + 10));
  });

  globalShortcut.register('Ctrl+Shift+Down', () => {
    setBoost(Math.max(0, boostLevel - 10));
  });
}

// IPC Handlers
ipcMain.handle('get-boost-level', () => boostLevel);
ipcMain.handle('set-boost-level', (_, level) => {
  setBoost(level);
  return boostLevel;
});

ipcMain.handle('set-mute', (_, mute) => {
  setMute(mute);
  return isMuted;
});

ipcMain.handle('get-engine-status', () => getAudioEngineStatus());

ipcMain.handle('install-apo', () => {
  const possiblePaths = [
    path.join(process.resourcesPath || '', 'installer', 'EqualizerAPO-Installer.exe'),
    path.join(__dirname, '../installer/EqualizerAPO-Installer.exe'),
    path.join(app.getAppPath(), 'installer', 'EqualizerAPO-Installer.exe'),
  ];

  for (const p of possiblePaths) {
    if (fs.existsSync(p)) {
      exec(`explorer.exe "${p}"`);
      return { success: true, message: 'Instalador do Equalizer APO iniciado!' };
    }
  }

  return { success: false, message: 'Arquivo do instalador não localizado.' };
});

ipcMain.handle('get-audio-sessions', async () => {
  const sessions = await runBridge(['sessions']);
  if (Array.isArray(sessions) && sessions.length > 0) {
    return sessions;
  }
  return [];
});

ipcMain.handle('set-app-volume', async (_, pid, volume) => {
  const result = await runBridge(['set-app-volume', String(pid), String(volume)]);
  return result && result.ok === true;
});

ipcMain.handle('set-limiter', (_, enabled) => {
  limiterEnabled = enabled;
  return true;
});

ipcMain.handle('get-autostart', () => {
  const settings = app.getLoginItemSettings();
  return settings.openAtLogin;
});

ipcMain.handle('set-autostart', (_, enable) => {
  app.setLoginItemSettings({
    openAtLogin: enable,
    path: app.getPath('exe'),
  });
  return enable;
});

ipcMain.on('minimize-window', () => mainWindow?.hide());
ipcMain.on('minimize-to-tray', () => mainWindow?.hide());
ipcMain.on('close-window', () => {
  mainWindow?.hide();
});

ipcMain.on('open-external', (_, url) => {
  if (typeof url === 'string' && (url.startsWith('https://') || url.startsWith('http://'))) {
    shell.openExternal(url);
  }
});

// ── Auto-Update IPC Handlers ─────────────────────────────────────────────

ipcMain.handle('check-for-updates', async () => {
  const currentVersion = app.getVersion();
  const update = await checkForUpdates(currentVersion);
  if (update && mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('update-available', update);
  }
  return update; // null se já está na última versão
});

ipcMain.handle('download-and-install-update', async (_, updateInfo) => {
  const tempDir = app.getPath('temp');
  const destPath = path.join(tempDir, updateInfo.fileName);

  try {
    await downloadUpdate(updateInfo.downloadUrl, destPath, (percent) => {
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('update-download-progress', percent);
      }
    });

    // Lança o instalador e encerra o VolumeMax para permitir a atualização
    exec(`"${destPath}"`, { detached: true });
    setTimeout(() => {
      app.isQuitting = true;
      app.quit();
    }, 1500);

    return { success: true };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

// App lifecycle
app.whenReady().then(async () => {
  createWindow();
  createTray();
  registerHotkeys();

  // Sync initial system volume
  const status = await runBridge(['status']);
  if (status && typeof status.masterVolume === 'number') {
    if (boostLevel === 100) {
      boostLevel = Math.round(status.masterVolume * 100);
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('boost-changed', boostLevel);
      }
    }
  }

  // Verifica atualizações em segundo plano 5s após iniciar
  setTimeout(async () => {
    try {
      const update = await checkForUpdates(app.getVersion());
      if (update && mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('update-available', update);
      }
    } catch { /* silencioso */ }
  }, 5000);
});

app.on('window-all-closed', () => {
  // Mantém app ativo na bandeja
});

app.on('activate', () => {
  if (!mainWindow) createWindow();
  else showWindow();
});

app.on('will-quit', () => {
  globalShortcut.unregisterAll();
});
